name: cd

on:
  push:
    branches: ["main"]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  Build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        cd GitTetsingDemo
        pod install --repo-update
      shell: bash

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.1'

    - name: Build
      run: |
        cd GitTetsingDemo
        xcodebuild build -workspace GitTetsingDemo.xcworkspace -scheme GitTetsingDemo clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    - name: Run tests
      run: |
        cd GitTetsingDemo
        xcodebuild test -workspace GitTetsingDemo.xcworkspace -scheme GitTetsingDemo clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
